 live_config_reload = true
 
 [shell]
 program = "/bin/zsh"
 
 [env]
 term = "xterm-256color"

 
 [window]
 startup_mode="Windowed"
 decorations = "buttonless"
 dynamic_padding = false
 
# [window.padding]
# x = 10
# y = 10
 
 [font]
 size = 20.0
 
 [font.bold]
 family = "JetBrainsMono Nerd Font"
 style = "Heavy"
 
 [font.bold_italic]
 family = "JetBrainsMono Nerd Font"
 style = "Heavy Italic"
 
 [font.italic]
 family = "JetBrainsMono Nerd Font"
 style = "Italic"
 
 [font.normal]
 family = "JetBrainsMono Nerd Font"
 style = "Medium"
 
 
